### PR TITLE
Updates for Kegbot 1.2.3, fixes for Heroku, etc.

### PR DESCRIPTION
**Pull request by ravenium**
Updated the requirements due to some outdated packages tanking s3 and Celery.

NewRelic has updated their free tier to "Wayne", changed appropriately.

--all is deprecated and implicit per kegbot updates.

Slight bug introduced - I tried to add an os.environ[] dict key for DEBUG mode, but I couldn't get it to toggle properly as a boolean, even when I cast it as such.  Therefore the DEBUG mode is set to False by default (as with my last commit that got it functioning).  Change as needed.

Also note that run_gunicorn is deprecated and may disappear in the future.

### CODE REVIEW

**Comment by szechyjs** [comment]
can you squash/rebase this?

**Comment by robertmaxrees** [comment]
@szechyjs fwiw you can configure the repo to squash commits when you merge PRs: https://github.com/blog/2141-squash-your-commits

**Comment by szechyjs** [comment]
thanks, i remember reading about that feature. i had to click accept pull request first before the drop down was displayed.

**Comment by ravenium** [comment]
Sorry about that - I was so excited that we got it working that I forgot I'd made a few too many commits.

**Pull request merged**
